### ISSUE TITLE
Validate arguments

### ISSUE THREAD

**Issue by kevinkuszyk** [CityOfYork/rs-deploy#7]
We need to validate arguments.  For example executing

```
rsdeploy.exe create-datasources
```
results in:

```
2016-01-18 17:40:30.0865 ERROR System.NullReferenceException: Object reference not set to an instance of an object.
   at CYC.RsDeploy.Console.Verbs.CreateDatasourcesVerb.Process() in C:\Projects\rs\src\CYC.RsDeploy.Console\Verbs\CreateDatasourcesVerb.cs:line 28
   at CYC.RsDeploy.Console.Program.CreateDatasources(Object options) in C:\Projects\rs\src\CYC.RsDeploy.Console\Program.cs:line 62
   at CYC.RsDeploy.Console.Program.OnVerb(String verb, Object options) in C:\Projects\rs\src\CYC.RsDeploy.Console\Program.cs:line 36
System.NullReferenceException: Object reference not set to an instance of an object.
   at CYC.RsDeploy.Console.Verbs.CreateDatasourcesVerb.Process() in C:\Projects\rs\src\CYC.RsDeploy.Console\Verbs\CreateDatasourcesVerb.cs:line 28
   at CYC.RsDeploy.Console.Program.CreateDatasources(Object options) in C:\Projects\rs\src\CYC.RsDeploy.Console\Program.cs:line 62
   at CYC.RsDeploy.Console.Program.OnVerb(String verb, Object options) in C:\Projects\rs\src\CYC.RsDeploy.Console\Program.cs:line 36
```

**Comment by kevinkuszyk** [comment]
It's in 1.1.
